[package]
name = "ungoliant"
version = "0.1.0"
authors = ["Pedro J. Ortiz <pedro@pjortiz.com>"]
edition = "2018"
description = "A mysterious project named after a spider that consumes everything."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = { version = "1.0.20", features= ["miniz-sys"]}
