[package]
name = "ungoliant"
version = "0.1.0"
authors = ["Pedro J. Ortiz <pedro@pjortiz.com>"]
edition = "2018"
description = "The pipeline for the OSCAR corpus."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
reqwest = { version = "0.11", features = ["blocking", "stream", "rustls-tls"] }
flate2 = { version = "1.0.20", features= ["miniz-sys"]}
futures-core = "0.3"
futures-util = "0.3"
futures = "0.3"
structopt = "0.3.21"
env_logger = "0.8.3"
log = "*"
itertools = "0.10.0"
tokio = { version = "1", features = ["full"] }
tokio-util = {version="0.6.6", features=["compat"]}
libflate = "1"
warc = {git = "https://github.com/jedireza/warc"}
fasttext = "0.5"
bytes = "1"

[dev-dependencies]
sha-1 = "0.9"