[package]
name = "ungoliant"
version = "0.1.0"
authors = ["Julien Abadji <julien.e.abadji@gmail.com, Pedro J. Ortiz <pedro@pjortiz.com>"]
edition = "2018"
description = "The pipeline for the OSCAR corpus."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
reqwest = { version = "0.11", default-features=false, features = ["rustls-tls", "blocking", "stream"] }
flate2 = { version = "1.0.20"}
futures-core = "0.3"
futures-util = "0.3"
futures = "0.3"
structopt = "0.3.21"
env_logger = "0.8.3"
log = "*"
itertools = "0.10.0"
tokio = { version = "1", features = ["full"] }
tokio-util = {version="0.6.6", features=["compat"]}
libflate = "1"
warc = {git = "https://github.com/uinelj/warc", features = ["with_serde"]}
fasttext = "0.6"
bytes = "1"
rayon = "1"
twox-hash = "1.6"
crossbeam = "0.8.0"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
runiq = { git ="https://github.com/uinelj/runiq"}
[dev-dependencies]
sha-1 = "0.9"
criterion = "0.3"
serial_test = "0.5.1"

[[bench]]
name = "fasttext_bench"
harness = false

[[bench]]
name = "pipeline_bench_rayon"
harness = false
