[package]
name = "ungoliant"
version = "0.1.0"
authors = ["Pedro J. Ortiz <pedro@pjortiz.com>"]
edition = "2018"
description = "The pipeline for the OSCAR corpus."
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13"
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = { version = "1.0.20", features= ["miniz-sys"]}
structopt = "0.3.21"
env_logger = "0.8.3"
log = "*"
rayon = "1.5"
itertools = "0.10.0"
libflate = "1"
warc = {git = "https://github.com/jedireza/warc"}